export enum MODEL_FIELD_TYPES {
  text = "text",
  digit = "digit",
  avatar = "avatar",
  cascader = "cascader",
  checkbox = "checkbox",
  code = "code",
  color = "color",
  date = "date",
  dateMonth = "dateMonth",
  dateQuarter = "dateQuarter",
  dateRange = "dateRange",
  dateTime = "dateTime",
  dateTimeRange = "dateTimeRange",
  dateWeek = "dateWeek",
  dateYear = "dateYear",
  fromNow = "fromNow",
  image = "image",
  money = "money",
  jsonCode = "jsonCode",
  password = "password",
  percent = "percent",
  progress = "progress",
  radio = "radio",
  radioButton = "radioButton",
  rate = "rate",
  second = "second",
  select = "select",
  switch = "switch",
  textarea = "textarea",
  time = "time",
  timeRange = "timeRange",
  treeSelect = "treeSelect",
}

export const MODEL_FIELD_TYPE_MAP = new Map()
  .set(MODEL_FIELD_TYPES.text, String)
  .set(MODEL_FIELD_TYPES.digit, Number);
